name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main  # Reemplaza con el nombre de tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Carpeta que contiene tu index.html

